name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

    - name: Build with Gradle Wrapper
      run: ./gradlew build -x test
    
  CD:
    runs-on: ubuntu-latest
    needs: CI 
    steps:
    
    - name: Run scripts in server
      uses: appleboy/ssh-action@v0.1.9
      with:
        key: ${{ secrets.SSH_KEY }}
        host: ${{ secrets.SERVER_IP }}
        username: ubuntu
        port: 22
        script: |
          cd ForLionz12_BE/
          git pull
          PID=$(lsof -t -i:8080)
          kill $PID
          cd build/libs/
          nohup java -jar site-0.0.1-SNAPSHOT.jar > /dev/null 2> /dev/null < /dev/null &
